[package]
name = "joe_learns_winit_wgpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = {version = "*", features = ["rwh_05"]}
wgpu = "*"
pollster = "*"
env_logger = "*"